### ISSUE TITLE
Unable to compile AT32F402/405

### ISSUE THREAD

**Issue by Xelus22** [zhaqian12/Cherryuf2#3]
Unable to compile with no modifications 

Both of these commands fail with the same error.
`make BOARD=at32f405ccu7_hs all`
`make BOARD=at32f405ccu7_fs all` 

![image](https://github.com/zhaqian12/Cherryuf2/assets/17491233/b405f824-325b-4e68-9d81-d3e2cad8d907)

EDIT: 
I was able to fix it but I need to edit core files.

![image](https://github.com/zhaqian12/Cherryuf2/assets/17491233/8f5f34b8-b3b9-44d8-9756-776744ffc5b9)

![image](https://github.com/zhaqian12/Cherryuf2/assets/17491233/1c348990-8338-46d7-b094-fdd55806c0e7)

**Comment by zhaqian12** [comment]
Sorry. This is a compatibility issue between submodules of different authors.
