### ISSUE TITLE
How do I modify the file for STM32F072

### ISSUE THREAD

**Issue by CMMS-Freather** [zhaqian12/Cherryuf2#8]
Hi there, 
A bit newbie to do source code modification
I want to have cherryuf2 work with stm32f072. I was able to flash in the uf2 bootloader to my chip, but after drag and drop my uf2 file, it doesnt auto eject and load the application. Would you mind let me know which vector do I need to modify in app or bootloader?
Greatly appreciated

**Comment by zhaqian12** [comment]
define BOARD_VECTOR_REDIRECT_BOOTLOADER macro.
